server.port: 8081
server.servlet.context-path: /order-api

spring:
  application.name: OrderService
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: orderdb
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    placeholders:
        schema_name: orderdb
  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: postgres
    hikari:
      schema: orderdb
    driver-class-name: org.postgresql.Driver