### Configure Debezium
POST http://localhost:8083/connectors
Content-Type: application/json

{
  "name": "order-connector",
  "config": {
    "connector.class": "io.debezium.connector.postgresql.PostgresConnector",
    "tasks.max": "1",
    "database.hostname": "postgres",
    "database.port": "5432",
    "database.user": "postgres",
    "database.password": "postgres",
    "database.dbname": "orderdb",
    "database.server.name": "orderdb_server",
    "plugin.name": "pgoutput",
    "slot.name": "debezium_slot",
    "publication.name": "order_publication",
    "publication.autocreate.mode": "filtered",
    "schema.include.list": "orderdb",
    "table.include.list": "orderdb.order",
    "topic.prefix": "cdc"
  }
}


### Delete Configuration
DELETE http://localhost:8083/connectors/order-connector
